version: '2.1'

services:
  nginx:
    image: nginx
    ports:
        - "883:80"
    depends_on:
      tomcat:
        condition: service_healthy
    volumes:
       - ./html:/opt/app

  postgres:
    image: portgres
    restart: always
    ports:
      - "5432:5432"
  tomcat:
    build: tomcat
    ports:
      - "8080:8080"
    links:
      - postgres